In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_colwidth', None)
from IPython.display import Image

In [3]:
#Read files:
train = pd.read_csv("train_kOBLwZA.csv")

In [6]:
data = train.copy()

In [7]:
data.apply(lambda x: sum(x.isnull()))

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [18]:
data.dropna(inplace= True)

In [19]:
data.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [8]:
data.describe()

Item_Weight  Item_Visibility     Item_MRP  Outlet_Establishment_Year  \
count  7060.000000      8523.000000  8523.000000                8523.000000   
mean     12.857645         0.066132   140.992782                1997.831867   
std       4.643456         0.051598    62.275067                   8.371760   
min       4.555000         0.000000    31.290000                1985.000000   
25%       8.773750         0.026989    93.826500                1987.000000   
50%      12.600000         0.053931   143.012800                1999.000000   
75%      16.850000         0.094585   185.643700                2004.000000   
max      21.350000         0.328391   266.888400                2009.000000   

       Item_Outlet_Sales  
count        8523.000000  
mean         2181.288914  
std          1706.499616  
min            33.290000  
25%           834.247400  
50%          1794.331000  
75%          3101.296400  
max         13086.964800

In [9]:
data.apply(lambda x: len(x.unique()))

Item_Identifier              1559
Item_Weight                   416
Item_Fat_Content                5
Item_Visibility              7880
Item_Type                      16
Item_MRP                     5938
Outlet_Identifier              10
Outlet_Establishment_Year       9
Outlet_Size                     4
Outlet_Location_Type            3
Outlet_Type                     4
Item_Outlet_Sales            3493
dtype: int64

In [10]:
data.shape

(8523, 12)

In [11]:
#Filter categorical variables
categorical_columns = [x for x in data.dtypes.index if data.dtypes[x]=='object']
#Exclude ID cols and source:
categorical_columns = [x for x in categorical_columns if x not in ['Item_Identifier','Outlet_Identifier','source']]

In [13]:
#Print frequency of categories
for col in categorical_columns:
    print('\nFrequency of Categories for varible %s'%col)
    print(data[col].value_counts())


Frequency of Categories for varible Item_Fat_Content
Low Fat    5089
Regular    2889
LF          316
reg         117
low fat     112
Name: Item_Fat_Content, dtype: int64

Frequency of Categories for varible Item_Type
Fruits and Vegetables    1232
Snack Foods              1200
Household                 910
Frozen Foods              856
Dairy                     682
Canned                    649
Baking Goods              648
Health and Hygiene        520
Soft Drinks               445
Meat                      425
Breads                    251
Hard Drinks               214
Others                    169
Starchy Foods             148
Breakfast                 110
Seafood                    64
Name: Item_Type, dtype: int64

Frequency of Categories for varible Outlet_Size
Medium    2793
Small     2388
High       932
Name: Outlet_Size, dtype: int64

Frequency of Categories for varible Outlet_Location_Type
Tier 3    3350
Tier 2    2785
Tier 1    2388
Name: Outlet_Location_Type, dtype: int64

F

In [23]:
print(data.columns)
X = data[['Item_Weight', 'Item_MRP']]
y = data['Item_Outlet_Sales']

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')


In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=27)

# MinMaxScaler

In [25]:
# data normalization with sklearn
from sklearn.preprocessing import MinMaxScaler

In [26]:
# fit scaler on training data
norm = MinMaxScaler().fit(X_train)

# transform training data
X_train_norm = norm.transform(X_train)
print("Scaled Train Data: \n\n")
print(X_train_norm)

# transform testing dataabs
X_test_norm = norm.transform(X_test)
print("\n\nScaled Test Data: \n\n")
print(X_test_norm)

Scaled Train Data: 


[[0.24412027 0.37504758]
 [0.43435546 0.09165993]
 [0.66656743 0.02192283]
 ...
 [0.1947008  0.54095015]
 [0.99404585 0.85616555]
 [0.108961   0.33292325]]


Scaled Test Data: 


[[0.96129801 0.02574614]
 [0.1947008  0.94129697]
 [0.64275082 0.6782561 ]
 ...
 [0.14855612 0.32286201]
 [0.93450432 0.6419228 ]
 [0.43435546 0.2760537 ]]


# StandardScaler

In [27]:
# data standardization with  sklearn
from sklearn.preprocessing import StandardScaler

In [30]:
# fit scaler on training data
norm = StandardScaler().fit(X_train)

# transform training data
X_train_norm = norm.transform(X_train)
print("Scaled Train Data: \n\n")
print(X_train_norm)

# transform testing dataabs
X_test_norm = norm.transform(X_test)
print("\n\nScaled Test Data: \n\n")
print(X_test_norm)

Scaled Train Data: 


[[-0.89377575 -0.35899568]
 [-0.21016664 -1.42687302]
 [ 0.6242858  -1.68966027]
 ...
 [-1.07136434  0.26616775]
 [ 1.8010777   1.45398019]
 [-1.37946986 -0.51773096]]


Scaled Test Data: 


[[ 1.68339851 -1.67525307]
 [-1.07136434  1.77477721]
 [ 0.53870094  0.78357176]
 ...
 [-1.23718502 -0.5556443 ]
 [ 1.58711553  0.64665858]
 [-0.21016664 -0.73202999]]


In [31]:
# training an SVR model
from  sklearn.svm import SVR
# measuring RMSE score
from sklearn.metrics import mean_squared_error

# SVR
svr = SVR(kernel='rbf',C=5)

rmse = []

# raw, normalized and standardized training and testing data
trainX = [X_train, X_train_norm, X_train_stand]
testX = [X_test, X_test_norm, X_test_stand]

# model fitting and measuring RMSE
for i in range(len(trainX)):
    
    # fit
    svr.fit(trainX[i],y_train)
    # predict
    pred = svr.predict(testX[i])
    # RMSE
    rmse.append(np.sqrt(mean_squared_error(y_test,pred)))

# visualizing the result    
df_svr = pd.DataFrame({'RMSE':rmse},index=['Original','Normalized','Standardized'])
df_svr

RMSE
Original      1115.721058
Normalized    1150.923047
Standardized  1150.923047

In [38]:
# training a KNN model
from sklearn.neighbors import KNeighborsRegressor
# measuring RMSE score
from sklearn.metrics import mean_squared_error

# knn 
knn = KNeighborsRegressor(n_neighbors=7)

rmse = []

# raw, normalized and standardized training and testing data
trainX = [X_train, X_train_norm, X_train_stand]
testX = [X_test, X_test_norm, X_test_stand]

# model fitting and measuring RMSE
for i in range(len(trainX)):
    
    # fit
    knn.fit(trainX[i],y_train)
    # predict
    pred = knn.predict(testX[i])
    # RMSE
    rmse.append(np.sqrt(mean_squared_error(y_test,pred)))

# visualizing the result
df_knn = pd.DataFrame({'RMSE':rmse},index=['Original','Normalized','Standardized'])
df_knn

RMSE
Original      1169.491000
Normalized    1334.253086
Standardized  1148.844577

# RobustScaler

In [32]:
from sklearn.preprocessing import RobustScaler

In [33]:
# fit scaler on training data
norm = RobustScaler().fit(X_train)

# transform training data
X_train_norm = norm.transform(X_train)
print("Scaled Train Data: \n\n")
print(X_train_norm)

# transform testing dataabs
X_test_norm = norm.transform(X_test)
print("\n\nScaled Test Data: \n\n")
print(X_test_norm)

Scaled Train Data: 


[[-0.4837523  -0.25694186]
 [-0.09196812 -0.98055353]
 [ 0.38626609 -1.15862259]
 ...
 [-0.58553035  0.16667941]
 [ 1.06069896  0.97156113]
 [-0.76210914 -0.36450355]]


Scaled Test Data: 


[[ 0.99325567 -1.14886003]
 [-0.58553035  1.18893859]
 [ 0.33721643  0.51728108]
 ...
 [-0.68056407 -0.39019427]
 [ 0.9380748   0.42450641]
 [-0.09196812 -0.50971619]]


# Maximum Absolute Scaling

In [34]:
from sklearn.preprocessing import MaxAbsScaler

In [35]:
# fit scaler on training data
norm = MaxAbsScaler().fit(X_train)

# transform training data
X_train_norm = norm.transform(X_train)
print("Scaled Train Data: \n\n")
print(X_train_norm)

# transform testing dataabs
X_test_norm = norm.transform(X_test)
print("\n\nScaled Test Data: \n\n")
print(X_test_norm)

Scaled Train Data: 


[[0.40538642 0.44878533]
 [0.55503513 0.19883442]
 [0.73770492 0.13732556]
 ...
 [0.36651054 0.59511316]
 [0.99531616 0.87313649]
 [0.29906323 0.41163123]]


Scaled Test Data: 


[[0.96955504 0.14069776]
 [0.36651054 0.9482233 ]
 [0.71896956 0.71621846]
 ...
 [0.33021077 0.40275711]
 [0.94847775 0.68417211]
 [0.55503513 0.36147169]]


# Scaling to vector unit norm

In [36]:
from sklearn.preprocessing import Normalizer

In [37]:
# fit scaler on training data
norm = Normalizer().fit(X_train)

# transform training data
X_train_norm = norm.transform(X_train)
print("Scaled Train Data: \n\n")
print(X_train_norm)

# transform testing dataabs
X_test_norm = norm.transform(X_test)
print("\n\nScaled Test Data: \n\n")
print(X_test_norm)

Scaled Train Data: 


[[0.07207221 0.99739942]
 [0.21793671 0.9759629 ]
 [0.3948213  0.91875793]
 ...
 [0.0492072  0.99878859]
 [0.09081317 0.99586795]
 [0.05802172 0.99831532]]


Scaled Test Data: 


[[0.48276313 0.87575097]
 [0.03090555 0.99952231]
 [0.08004558 0.9967912 ]
 ...
 [0.06544615 0.9978561 ]
 [0.11022386 0.99390679]
 [0.12191652 0.99254036]]
